version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ".env"

  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/gallerhyme
    ports:
      - "3001:3001"
    links:
      - db
      - react
    depends_on:
      - db
      - react

  react:
    build: .
    volumes:
      - ./client/node_modules
    working_dir: /gallerhyme/client
    command: yarn start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development