export const FETCHING_USER_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_USER_ERROR = "FETCHING_DATA_ERROR";

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_USER = "FETCH_USER";
